apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAZWA-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NAZWA
  template:
    metadata:
      labels:
        app: NAZWA
    spec:
      containers:
        - image: containous/whoami
          name: whoami
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: NAZWA-svc
spec:
  type: ClusterIP
  selector:
    app: NAZWA
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: NAZWA
spec:
  rules:
    - host: NAZWA.k8s.musur.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: NAZWA-svc
                port:
                  number: 80
